eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
      
microservice:
  apigateway:
    endpoints:
      endpoint:
        uri: http://localhost:8080
  customer-service:
    endpoints:
      endpoint:
        uri: http://customer-service/customerms/customers
  order-service:
    endpoints:
      endpoint:
        uri: http://order-service/orderms/orders
  product-service:
    endpoints:
      endpoint:
        uri: http://product-service/productms/products
